#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
# redirection must be a “301 Moved Permanently”

REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
CUSTOM_404="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"


sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "/server_name _;/a $CUSTOM_404" /etc/nginx/sites-available/default

sudo service nginx restart
