#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

echo "
frontend haproxynode
    bind *:80
    mode http
    default_backend web-servers
backend web-servers
        balance roundrobin
        server web-01 54.237.120.151:80 check
        server web-02 100.25.36.240:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
