#!/usr/bin/env bash
# changing to port 80

# sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
