#!/usr/bin/env bash                                                                                                                        
# changing port                                                                                                                        

sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default                                                                             
sudo service nginx restart
