#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
i=0; while [ $i -le 12 ]
do
	echo "Hour: $i"
	i=$(( i+1 ))
	while [ $i -le 59 ]
	do
		echo "$i"
		i=$(( i+1 ))
	done
done
