#!/usr/bin/env bash
# script that gives you information about the school file

if [ -e "school" ]
then 
	echo "school file exists"
	if [ -s "school" ]
	then 
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if test -f "school"
	then
		echo "school file is a regular file"
	fi
else
	echo "school file doesnt exist"
fi
