#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/localhosts ~/hosts_new
sed -i '/127/ i 127.0.0.2 localhost\n8.8.8.8 facebook.com' ~/hosts_new
cp -f ~/hosts_new /etc/hosts
